version: "3.5"

services:
  backend:
    container_name: backend
    build: ./backend/
    command: bash -c "rm -f tmp/pids/server.pid || true && bundle exec rails s -p 3000 -b '0.0.0.0'"
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/backend/
    links:
      - inclucad_db
    stdin_open: true
    tty: true

  frontend:
    container_name: frontend
    build: ./frontend/
    ports:
      - "80:3000"
    volumes:
      - '.:/app'
      - '/app/node_modules'


  inclucad_db:
    container_name: inclucad_db
    image: mongo
    restart: always
    volumes:
      - /data/db
      # - ./mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    ports:
      - "29020:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: "${DB_USER}"
      MONGO_INITDB_ROOT_PASSWORD: "${DB_PASS}"
      MONGO_INITDB_DATABASE: "${DB_NAME}"
    command: mongod
